// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func initMessages() Messages {
	string2 := provideHello()
	string3 := provideWorld()
	messages := Messages{string2, string3}
	return messages
}
