// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/goforj/wire"
)

// Injectors from wire.go:

func initHandlers() Handlers {
	barHandler := NewBarHandler()
	fooHandler := NewFooHandler()
	wrapped := WrapHandler(fooHandler)
	mainWrapped := WrapHandler(barHandler)
	handlers := Handlers{wrapped, mainWrapped}
	return handlers
}

// wire.go:

// Reproduce GSM pattern: constructors in a separate Set, Slice in another Set that imports it.
var ConstructorSet = wire.NewSet(
	NewFooHandler,
	NewBarHandler,
)

var SliceSet = wire.NewSet(
	ConstructorSet, wire.Slice(new(Handlers),
		WrapHandler[FooEvent],
		WrapHandler[BarEvent],
	),
)
